package test;

import static org.junit.Assert.*;

import java.sql.SQLException;

import org.hamcrest.Matchers;
import org.junit.Assert;

//import junit.framework.Assert;

import org.junit.Test;
import com.mysql.jdbc.Connection;
import dados.Conexao2;

public class Conexao2Test {
	private static final String bd= "camilaBD";
	private static final String user= "camila";
	private static final String invalidUser = "Cristhian";
	private static final String password= "camila";
	private Conexao2 conexao;

	@Test
	public void testConexaoOk() {
		//fail("Not yet implemented");
		conexao =new Conexao2(bd,user,password);
		java.sql.Connection conn = null;
		try {
			conn =conexao.getConexao();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			//e.printStackTrace();
			Assert.fail("Conexao com falha ");
		}
		Assert.assertThat(conn, Matchers.notNullValue());		
	}
	
	@Test 
	public void testConexaoErr(){
		conexao = new Conexao2(bd,invalidUser,password);
		java.sql.Connection conn = null;		
		try {
			conn = conexao.getConexao();
			//Assert.fail("La conexao tem falha");
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			//e.printStackTrace();
			Assert.assertThat(e, Matchers.isA(SQLException.class));
		}
		Assert.assertThat(conn, Matchers.notNullValue());
	}

}
